# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44c6efbf20fa3ed6e58e41363d26106100cd6fcdcf0c8891c140eec6a28b09a350495791667a549ba2b8d50fc5a716a1bb13a1eab0ea99423c4a174ab4d05014

test:
  secret_key_base: fdb0ec49c3aa82448ee134642b1dbb0124d40aa9aee7d6dca564acff8033dd3ef3d599367009c172410292a5149558e633ff564cd4db0511f1c23f5832d252c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
